<?php

function article_viewer_menu() {
    $items['article/%/%'] = array(
        'access arguments' => array('access content'),
        'page callback' => 'article_viewer_callback',
        'page arguments' => array(1,2),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function article_viewer_callback($js, $node_id) {
    $node = node_load($node_id);

    if ($js == 'nojs') {
        drupal_goto('node/' . $node_id);
    }

    $build = node_view($node);
    $html = render($build);

    $commands = array();
    $commands[] = ajax_command_html('#ajax-display', $html);

    print ajax_render($commands);
    exit;
}
